feature: US001 view job roles
GoodDayOrg/GDO-frontend pull request #5
Opened 2024-08-27 13:56 UTC by DariuszMech

2024-08-27 14:12 UTC, pedrosmake approved these changes

2024-08-27 15:08 UTC, pedrosmake commented on src/services/JobRoleService.ts
> +        console.log(e);
Please remove this.

2024-08-28 08:24 UTC, Alicja-Kainos commented on views/job-role-list.html
> +    <h3>Job Role List</h3>
in theory it should be one tab to right, because h3 and all other sections are nested within the div

2024-08-28 08:25 UTC, Alicja-Kainos commented on test/unit/services/JobRoleServiceTests.ts
> +          await getAllJobRoles();
please add expect true to be false or false to be true after each expression that should return the error -> if error is not thrown, test will fail. Right now false pass is possible

2024-08-28 08:26 UTC, Alicja-Kainos requested changes
Please correct indentation and tests

2024-08-28 08:46 UTC, DariuszMech commented
> Please correct indentation and tests

done

2024-08-28 09:02 UTC, Alicja-Kainos approved these changes

2024-08-30 08:33 UTC, merged